# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 106b372e15d5b048eb3fad49063759f3da24170bb069f25ac09d464c51f7b479fa6e7761bbdfc2f1a2f25f5b99264392273029c7def31e2eba496ebd44508d8e

test:
  secret_key_base: fc4b8848e1673f9b7c57207a5ab5a9632288fe3ed11e22b732fce3c99bfec6f359a49c248482dd044d65836d68608b949c1ebc422dbb9355832c0954442d8e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
